[workspace]
members = [
  "prisma-models",
  "query-engine/connectors/connector",
  "query-engine/connectors/sql-connector",
  "query-engine/prisma",
  "query-engine/native-bridge",
  "query-engine/core",
]
