[workspace]
members = [
  "prisma-models",
  "migration-engine",
  "query-engine/connectors/connector",
  "query-engine/connectors/sql-connector",
  "query-engine/prisma",
  "query-engine/native-bridge",
  "query-engine/core",
  "libs/prisma-datamodel",
  "libs/inflector",
]
