[package]
name = "connector"
version = "0.1.0"
authors = []
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
once_cell = "0.1"
prisma-query = { git = "https://github.com/prisma/prisma-query.git" }
prisma-models = { path = "../../../prisma-models" }
prisma-common = { path = "../../../libs/prisma-common" }
