[package]
name = "sql-migration-connector"
version = "0.1.0"
authors = ["Marcus Böhm <boehm@prisma.io>"]
edition = "2018"

[dependencies]
migration-connector = { path = "../migration-connector" }
sql-schema-describer = { path = "../../../libs/sql-schema-describer" }
datamodel = { path = "../../../libs/datamodel/core" }
prisma-models = { path = "../../../libs/prisma-models" }
chrono = { version = "0.4" }
serde_json = "1.0"
serde = "1.0"
barrel = { version = "0.6.3-alpha.0", features = ["sqlite3", "mysql", "pg"] }
itertools = "0.8"
log = "0.4"
failure = "0.1"
quaint = { git = "https://github.com/prisma/quaint.git" }
sql-connection = { path  = "../../../libs/sql-connection" }
user-facing-errors = { path = "../../../libs/user-facing-errors" }
