[package]
name = "prisma-fmt"
version = "0.1.0"
authors = ["Emanuel Joebstl <emanuel.joebstl@gmail.com>"]
edition = "2018"

[dependencies]
datamodel = { path = "../libs/datamodel" }
clap = "2.33.0"
serde = { version = "1.0.90", features = ["derive"] }
serde_json = "1.0"