[package]
name = "core"
version = "0.1.0"
authors = ["Dominic Petrick <dompetrick@gmail.com>"]
edition = "2018"

[dependencies]
graphql-parser = "0.2.2"
Inflector = "0.11"
prisma-common = { path = "../../libs/prisma-common" }
prisma-models = { path = "../../prisma-models" }
connector = { path = "../connectors/connector" }