[package]
name = "sql-introspection-connector"
version = "0.1.0"
authors = ["Marcus Böhm <boehm@prisma.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
introspection-connector = { path = "../introspection-connector" }
sql-schema-describer = { path = "../../../libs/sql-schema-describer" }
prisma-inflector = { path = "../../../libs/prisma-inflector" }
datamodel = { path = "../../../libs/datamodel" }
prisma-query = { git = "https://github.com/prisma/prisma-query.git" }
failure = "0.1"
log = "0.4"
regex = "1.2"
url = "1.7"

[dev-dependencies]
fern = "0.5"
pretty_assertions = "0.6"
barrel = { version = "0.6.3-alpha.0", features = ["sqlite3", "mysql", "pg"] }

