[methods.listMigrationDirectories]
description = "List the names of the migrations in the migrations directory."
requestShape = "listMigrationDirectoriesInput"
responseShape = "listMigrationDirectoriesOutput"

[recordShapes.listMigrationDirectoriesInput]
description = """
The input to the `listMigrationDirectories` command.
"""

[recordShapes.listMigrationDirectoriesInput.fields.migrationsDirectoryPath]
description = "The location of the migrations directory."
shape = "string"

[recordShapes.listMigrationDirectoriesOutput.fields.migrations]
isList = true
description = """
The names of the migrations in the migration directory. Empty if no migrations are found.
"""
shape = "string"
