[package]
name = "introspection-core"
version = "0.1.0"
authors = ["Marcus Böhm <boehm@prisma.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
introspection-connector = { path = "../connectors/introspection-connector" }
sql-introspection-connector = { path = "../connectors/sql-introspection-connector" }
datamodel = { path = "../../libs/datamodel/core" }
url = "1.7"
failure = "0.1"

jsonrpc-core = "13.0"
jsonrpc-stdio-server = "13.0"
jsonrpc-derive = "13.0"
jsonrpc-core-client = "13.0"

serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"


[[bin]]
name = "introspection-engine"
path = "src/main.rs"

