on:
  repository_dispatch:
    types: [trigger-build]

jobs:
  build:
    name: ${{ github.event.client_payload.branch }} Windows engines build ${{ github.event.client_payload.commit }}
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.commit }}

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - uses: actions/upload-artifact@v2
        with:
          name: query-engine.exe-${{ github.event.client_payload.commit }}
          path: ${{ github.workspace }}/target/release/query-engine.exe
