name: Migration Engine
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  test-linux:
    name: "Test ${{ matrix.database.name }} on Linux"

    strategy:
      fail-fast: false
      matrix:
        database:
          - name: mssql_2017
            url: "sqlserver://localhost:1434;database=master;user=SA;password=<YourStrong@Passw0rd>;trustServerCertificate=true;socket_timeout=60;isolationLevel=READ UNCOMMITTED"
          - name: mssql_2019
            url: "sqlserver://localhost:1433;database=master;user=SA;password=<YourStrong@Passw0rd>;trustServerCertificate=true;socket_timeout=60;isolationLevel=READ UNCOMMITTED"
          - name: mysql_5_6
            url: "mysql://root:prisma@localhost:3309"
          - name: mysql_5_7
            url: "mysql://root:prisma@localhost:3306"
          - name: mysql_8
            url: "mysql://root:prisma@localhost:3307"
          - name: mysql_mariadb
            url: "mysql://root:prisma@localhost:3308"
          - name: postgres9
            url: "postgresql://postgres:prisma@localhost:5431"
          - name: postgres10
            url: "postgresql://postgres:prisma@localhost:5432"
          - name: postgres11
            url: "postgresql://postgres:prisma@localhost:5433"
          - name: postgres12
            url: "postgresql://postgres:prisma@localhost:5434"
          - name: postgres13
            url: "postgresql://postgres:prisma@localhost:5435"
          - name: sqlite
            url: sqlite
          - name: vitess_5_7
            url: "mysql://root:prisma@localhost:33577/test"
            shadow_database_url: "mysql://root:prisma@localhost:33578/shadow"
          - name: vitess_8_0
            url: "mysql://root:prisma@localhost:33807/test"
            shadow_database_url: "mysql://root:prisma@localhost:33808/shadow"

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: "Start ${{ matrix.database.name }}"
        run: make start-${{ matrix.database.name }}

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: migration-engine-${{ runner.os }}-cargo-${{ matrix.database.name }}-${{ hashFiles('**/Cargo.lock') }}

      - run: timeout 40m cargo test
        if: ${{ matrix.database.name != 'vitess_5_7' && matrix.database.name != 'vitess_8_0' }}
        working-directory: migration-engine/migration-engine-tests
        env:
          CLICOLOR_FORCE: 1
          TEST_DATABASE_URL: ${{ matrix.database.url }}

      - run: cargo test -- --test-threads=1
        if: ${{ matrix.database.name == 'vitess_5_7' || matrix.database.name == 'vitess_8_0' }}
        working-directory: migration-engine/migration-engine-tests
        env:
          CLICOLOR_FORCE: 1
          IS_VITESS: 1
          TEST_DATABASE_URL: ${{ matrix.database.url }}
          TEST_SHADOW_DATABASE_URL: ${{ matrix.database.shadow_database_url }}

  test-windows:
    strategy:
      fail-fast: false
      matrix:
        db:
          - name: mysql
            url: "mysql://root@localhost:3306?connect_timeout=20&socket_timeout=60"
          - name: mariadb
            url: "mysql://root@localhost:3306?connect_timeout=20&socket_timeout=60"
        rust:
          - stable
        os:
          - windows-latest

    runs-on: ${{ matrix.os }}

    name: "Test ${{ matrix.db.name }} on Windows"

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{matrix.rust}}

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ matrix.rust }}-${{ matrix.db.name }}-${{ hashFiles('**/Cargo.lock') }}

      - name: Install ${{ matrix.db.name }}
        run: choco install ${{ matrix.db.name }}

      - name: Run tests
        run: cargo test -p migration-engine-tests
        env:
          TEST_DATABASE_URL: ${{ matrix.db.url }}
